Clean up and working orb

diff --git a/src/commands/notify.yml b/src/commands/notify.yml
--- a/src/commands/notify.yml
+++ b/src/commands/notify.yml
@@ -11,9 +11,9 @@ commands:
         default: "${CIRCLE_PROJECT_REPONAME}"
         description: Project the build is from
         type: string
-      workflow:
-        default: ""
-        description: The name of the workflow
+      workflow_id:
+        default: "${CIRCLE_WORKFLOW_ID}"
+        description: A unique identifier for the workflow instance of the current job.
         type: string
       branch:
         default: "${CIRCLE_BRANCH}"
@@ -35,13 +35,67 @@ commands:
         default: "${CIRCLE_JOB}"
         description: The job name
         type: string
-      job_status:
+      xm_url:
+        default: "${XM_URL}"
+        description: The inbound integration url. This can be stored in the CircleCI UI as the 'XM_URL' env var
+        type: string
+    steps:
+    - run:
+        command: |
+          if [ -z "$BASH" ]; then
+            echo Bash not installed.
+            exit 1
+          fi
+        name: Provide error if non-bash shell
+    - run:
+        command: |
+          echo 'export XM_BUILD_STATUS="fail"' >> $BASH_ENV
+        name: xMatters - Setting Failure Condition
+        when: on_fail
+    - run:
+        command: |
+          echo 'export XM_BUILD_STATUS="success"' >> $BASH_ENV
+        name: xMatters - Setting Success Condition
+        when: on_success
+    - run:
+        command: |
+          # Provide error if no url is set and error. Otherwise continue
+          if [ -z "<< parameters.xm_url >>" ]; then
+            echo "NO XM_URL SET"
+            echo "Please input your XM_URL value either in the settings for this project, or as a parameter for this orb."
+            exit 1
+          fi
+
+          # Webhook properly set.
+          echo Generating event to xMatters
+          curl -X POST -H 'Content-type: application/json' \
+            --data \
+            "{\
+              \"properties\": {\
+                \"author\":     \"<< parameters.author >>\",\
+                \"project\":    \"<< parameters.project >>\",\
+                \"workflow_id\":   \"<< parameters.workflow_id >>\",\
+                \"branch\":     \"<< parameters.branch >>\",\
+                \"commit\":     \"<< parameters.commit >>\",\
+                \"build\":      \"<< parameters.build >>\",\
+                \"build_url\":  \"<< parameters.build_url >>\",\
+                \"job\":        \"<< parameters.job >>\",\
+                \"job_status\": \"$XM_BUILD_STATUS\" \
+              } \
+            }" "<< parameters.xm_url >>"
+        name: xMatters Inbound Command
+        shell: /bin/bash
+  notify_raw:
+    description: Generate an xMatters event with the given JSON payload
+    parameters:
+      json_payload:
         default: ""
-        description: The job status
+        description: The json object to send to xMatters. CHECKOUTTHEDOCSHERE
         type: string
       xm_url:
         default: ${XM_URL}
-        description: The inbound integration url. This can be stored in the CircleCI UI as the 'XM_URL' env var
+        description: Enter either your inbound integration url or use the CircleCI UI to add
+          your token under the 'XM_URL' env var
         type: string
     steps:
     - run:
@@ -58,24 +112,18 @@ commands:
             echo "NO XM_URL SET"
             echo "Please input your XM_URL value either in the settings for this project, or as a parameter for this orb."
             exit 1
-
+          fi
+          if [-z "<< parameters.json_payload >>" ]; then
+            echo "NO json_payload passed"
+            echo "Enter some json to pass into xMatters. CHECKOUTTHEDOCSHERE"
+            exit 1
+          fi
+          
           # Webhook properly set.
-          echo Generating event to xMatters
-          curl -X POST -H 'Content-type: application/json' \
-            --data \
-            '{
-              "properties": {
-                "author":     "<< parameters.author >>",
-                "project":    "<< parameters.project >>",
-                "workflow":   "<< parameters.workflow >>",
-                "branch":     "<< parameters.branch >>",
-                "commit":     "<< parameters.commit >>",
-                "build":      "<< parameters.build >>",
-                "build_url":  "<< parameters.build_url >>",
-                "job":        "<< parameters.job >>",
-                "job_status": "<< parameters.job_status >>"
-              } 
-            }' "<< parameters.xm_url >>" 
+          echo "Generating event to xMatters with payload '" << parameters.json_payload >> "'"
+          curl -X POST --header 'Content-type: application/json' \
+            --data '<< parameters.json_payload >>' \
+            "<< parameters.xm_url >>"          
         name: xMatters Inbound Command
         shell: /bin/bash
 description: |
@@ -90,16 +138,34 @@ examples:
              - image: <docker image>
           steps:
              - xmatters/notify:
-                xm_url:     ${XM_URL}
-                author:     ""
-                project:    ""
-                workflow:   ""
-                branch:     ""
-                commit:     ""
-                build:      ""
-                build_url:  ""
-                job:        ""
-                job_status: ""
+                xm_url:     $XM_URL
+                author:      ""
+                project:     ""
+                workflow_id: ""
+                branch:      ""
+                commit:      ""
+                build:       ""
+                build_url:   ""
+                job:         ""
+                job_status:  ""
+      orbs:
+        xmatters: circleci/xmatters@1.0.0
+      version: 2.1
+      workflows:
+        your-workflow:
+          jobs:
+          - build
+  notify_raw:
+    description: 'Notify some people via xMatters using a custom payload'
+    usage:
+      jobs:
+        build:
+          docker:
+             - image: <docker image>
+          steps:
+             - xmatters/notify_raw:
+                xm_url: ${XM_URL}
+                json_payload: '{ "properties": { "Job": "job name here", "Author": "Deon Sanders" }, "recipients": [{"id": "dsanders"}] }'
       orbs:
         xmatters: circleci/xmatters@1.0.0
       version: 2.1
